# Use a specific container image for the application
FROM ghcr.io/open-webui/open-webui:main

# Set the main working directory inside the container
WORKDIR /app/backend

# Copy the database file into the container
# and the core configuration is located in the Environment
# and Secret Environment settings
COPY --chown=$UID:$GID ./src/env.py /app/backend/open_webui/env.py
COPY --chown=$UID:$GID ./src/favicon.png /app/build/static/favicon.png
COPY --chown=$UID:$GID ./src/favicon.png /app/build/static/favicon.svg
COPY --chown=$UID:$GID ./src/favicon.png /app/build/static/favicon.ico
COPY --chown=$UID:$GID ./src/favicon.png /app/backend/open_webui/static/favicon.png
COPY --chown=$UID:$GID ./src/favicon.png /app/backend/open_webui/static/favicon.svg
COPY --chown=$UID:$GID ./src/favicon.png /app/backend/open_webui/static/favicon.ico

# Set the permission
RUN chmod 777 /app/backend/open_webui/env.py
RUN chmod 777 /app/build/static/favicon.png
RUN chmod 777 /app/backend/open_webui/static/favicon.png
RUN chmod 777 /app/backend/open_webui/static/favicon.svg
RUN chmod 777 /app/backend/open_webui/static/favicon.ico

# Open the port so the application can be accessed
EXPOSE 8800

# Start the application using the startup script
CMD ["bash", "start.sh"]
